[package]
name = "hook0-output-worker"
version = "0.3.0"
authors = ["David Sferruzza <david@hook0.com>", "François-Guillaume Ribreau <fg@hook0.com>"]
repository = "https://gitlab.com/hook0/hook0/-/tree/master/output-worker"
homepage = "https://www.hook0.com/"
description = "Worker for Hook0 Open-Source Webhooks as a service for SaaS"
edition = "2021"
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook-server", "events", "saas"]

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive", "env", "cargo", "wrap_help"] }
hex = "0.4.3"
hmac = "0.12.1"
hook0-sentry-integration = { path = "../sentry-integration", version = "0.1.0" }
humantime = "2.1.0"
itertools = "0.13.0"
log = "0.4.22"
reqwest = { version = "0.12.11", default-features = false, features = ["charset", "http2", "macos-system-configuration", "hickory-dns", "json"] }
serde = "1.0.217"
serde_json = "1.0.134"
sha2 = "0.10.8"
sqlx = { version = "0.8.2", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "uuid", "chrono", "json"] }
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros", "time"] }
uuid = { version = "1.11.0", features = ["v4"] }

[features]
default = ["reqwest-rustls-tls-webpki-roots"]
reqwest-rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots"]
reqwest-rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots"]
