[package]
name = "hook0-client"
version = "0.1.0"
edition = "2021"
description = "Rust SDK for Hook0 Open-Source Webhooks as a service for SaaS"
authors = ["David Sferruzza <david@hook0.com>", "François-Guillaume Ribreau <fg@hook0.com>"]
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook-server", "events", "saas"]
homepage = "https://www.hook0.com/"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
lazy-regex = "3.4.1"
log = "0.4.22"
reqwest = { version = "0.12.12", default-features = false, features = ["hickory-dns", "json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
thiserror = "2.0.10"
url = "2.5.4"
uuid = { version = "1.11.0", features = ["serde", "v4"] }

[features]
default = ["reqwest-rustls-tls-webpki-roots"]
reqwest-rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots"]
reqwest-rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots"]
